name: Package Builder

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: noble
          ROS_DISTRO: jazzy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
