name: Package Builder

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]

    steps:
      - run: dpkg-architecture >> "$GITHUB_ENV"

      - uses: jspricke/ros-deb-builder-action@main
        with:
          DEB_DISTRO: noble
          DEB_ARCH: ${{ env.DEB_HOST_ARCH }}
          ROS_DISTRO: jazzy
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: true
